[build-system]
requires = ["maturin>=1.9,<2.0"]
build-backend = "maturin"

[project]
name = "noderouter"
requires-python = ">=3.13"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]

dependencies = [
    "altair>=6.0.0",
    "bidict>=0.23.1",
    "colorcet>=3.1.0",
    "fast-paths>=0.1.0",
    "flet[all]>=0.84.0",
    "folium>=0.20.0",
    "highspy==1.14.0",
    "joblib>=1.5.3",
    "loguru>=0.7.3",
    "matplotlib>=3.10.8",
    "maturin>=1.13.1",
    "more-itertools>=11.1.0",
    "networkx>=3.6.1",
    "nwst-dw",
    "polars>=1.39.3",
    "psutil>=7.2.2",
    "pyarrow>=23.0.1",
    "pyvis>=0.3.2",
    "rustworkx>=0.17.1",
    "seaborn>=0.13.2",
    "shapely>=2.1.2",
    "ty>=0.0.29",
]

[tool.maturin]
python-source = "python"
profile = "release"
features = ["pyo3/extension-module", "python"]
bindings = "pyo3"
manifest-path = "Cargo.toml"

[tool.ty.environment]
extra-paths = ["./python/noderouter"]

[tool.ruff]
src = ["python/noderouter"]

[tool.pyright]
include = ["python/noderouter"]
extraPaths = ["python/noderouter"]

[tool.uv.sources]
nwst-dw = { path = "../../Rust/nwst_dw" }
