class DynamicCC:
    def __init__(self, adj_dict: dict[int, list[int]]) -> None: ...
    def insert_edge(self, u: int, v: int) -> int: ...
    def delete_edge(self, u: int, v: int) -> int: ...
    def query(self, u: int, v: int) -> bool: ...
    def cycle_basis(self, root: int | None) -> list[list[int]]: ...
    def node_connected_component(self, v: int) -> list[int]: ...
    def num_connected_components(self) -> int: ...
    def active_node_indices(self) -> list[int]: ...
    def isolate_node(self, v: int) -> None: ...
    def isolate_nodes(self, nodes: list[int]) -> None: ...
    def is_isolated(self, v: int, flush: bool|None) -> bool: ...
    def degree(self, v: int) -> int: ...
    def neighbors(self, v: int) -> list[int]: ...
    def potential_neighbors_from(self, v: int, from_indices: list[int], flush: bool| None) -> list[int]: ...