name = "pd_approximation"
type = "pd_approximation"
author = "thell"
description = "Primal dual approximation testing configuration."

# NOTE: DO NOT CHANGE THIS FILE: make a new copy for a new experiment

[actions]
baseline_tests = false
scaling_tests = true


[logger]
# My common format string.
# Basic output no timestamp, no filename
level = "SUCCESS"
format = "<level>{message}</level>"

# The loguru default format string.
# level = "DEBUG"
# format = "<green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> | <level>{level: <8}</level> | <cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> - <level>{message}</level>"

[exploration_data]
directed = true
edge_weighted = false
omit_great_ocean = true

# Solver is not used by the approximation functions but needs
# to be present for the current scaling tests setup and for
# solving the terminal clusters _after_ the approximation.
[solver]
jobs = 1

[solver.highs]
log_to_console = true
mip_feasibility_tolerance = 1e-4
mip_rel_gap = 1e-4
primal_feasibility_tolerance = 1e-4
random_seed = 12345
time_limit = inf

[subgraph]
generate_subgraph = false
greedy_components = true
sparsify_leafs = true
sparsify_zero_cost_nodes = true
include_shortest_paths = true
include_shortest_paths_all_terminals = true

[approximation]
approximate_solution = true
post_process_bridges = true

# reductions are not used by the approximation functions.
[reduction]
reduce_subgraph = false
# # non-terminal degree reductions
# ntd1 = true
# ntd2 = true
# ntd3 = false
# # fixed-terminal degree reductions
# ftd1 = false
# # contract neighboring fixed terminals
# ftn = false
# # steiner reductions
# sd = false # distance
# sb = false # bottleneck

[solution]
cleanup = true
validate = true
save = false
visualize = false
# compare_to = "mip_ip_baseline" # for visualization
