name = "generate_testcase"
type = "ip_baseline"
author = "thell"
description = "configuration for testing the generate_testcase functionality"

[logger]
# Basic output no timestamp, no filename
level = "DEBUG"
format = "<level>{message}</level>"

[exploration_data]
directed = true
edge_weighted = false
omit_great_ocean = true
