# visualize_nodes.py

"""
Visualizes the solution graph generated by the Steiner Forest solver
on the BDO map.

Edit the 'subgraph' entries at the bottom of the file.
"""

import io

import branca
import folium
import matplotlib.pyplot as plt
import matplotlib.colors as plt_colors
import webbrowser
import os
import tempfile
import folium.map
import rustworkx as rx
from folium.plugins import FeatureGroupSubGroup, GroupedLayerControl

import api_data_store as ds
from api_rx_pydigraph import set_graph_terminal_sets_attribute, subgraph_stable

import networkx as nx
from tree_decomp import BDONiceTreeManager

# from api_common import get_clean_exploration_data
# from api_exploration_graph import get_exploration_graph
# from api_rx_pydigraph import inject_super_root, set_graph_terminal_sets_attribute

from api_exploration_data import get_exploration_data

SUPER_ROOT = 99999
TILE_SCALE = 12800

MARKER_COLORS = [
    "blue",
    "gray",
    "lightred",
    "purple",
    "red",
    "lightblue",
    "lightgray",
    "black",
    # "white",
    "lightgreen",
    "green",
    "darkred",
    "darkblue",
    "cadetblue",
    "pink",
    "darkgreen",
    "darkpurple",
    "beige",
    "orange",
]

# Color Constants
MAIN_GRAPH_EDGE_COLOR = "darkturquoise"
SUBGRAPH_EDGE_COLOR = "yellow"
SUBGRAPH_OPTIMAL_EDGE_COLOR = "red"
MAIN_OPTIMAL_EDGE_COLOR = "yellow"
BASE_TOWN_COLOR = "green"
REGULAR_NODE_COLOR = "lightgray"
SUBGRAPH_NODE_COLOR = "yellow"
SUPER_ROOT_COLOR = "red"

# Line Thicknesses
MAIN_GRAPH_EDGE_WEIGHT = 1
SUBGRAPH_EDGE_WEIGHT = 6
MAIN_OPTIMAL_EDGE_WEIGHT = 6
SUBGRAPH_OPTIMAL_EDGE_WEIGHT = 2


def add_edges_from_graph(
    fg: folium.FeatureGroup,
    graph: rx.PyGraph | rx.PyDiGraph,
    color: str | None = None,
    weight: float = 0.75,
):
    """Add edges from the graph to the map."""
    for u_index, v_index in graph.edge_list():
        # Only include one edge of a bidirectional connection.
        if u_index > v_index and not graph.has_edge(v_index, u_index):
            continue

        u_node = graph[u_index]
        v_node = graph[v_index]
        if u_node["waypoint_key"] == 99999 or v_node["waypoint_key"] == 99999:
            continue

        start = u_node["position"]
        end = v_node["position"]

        start_lat = start["z"] / TILE_SCALE
        start_lng = start["x"] / TILE_SCALE
        end_lat = end["z"] / TILE_SCALE
        end_lng = end["x"] / TILE_SCALE

        folium.PolyLine(
            locations=[
                (start_lat, start_lng),
                (end_lat, end_lng),
            ],
            color=color,
            weight=weight,
            opacity=1,
            popup=f"Edge: {u_node['waypoint_key']} - {v_node['waypoint_key']}",
            tooltip=f"Edge: {u_node['waypoint_key']} - {v_node['waypoint_key']}",
            **{"interactive": True, "bubblingMouseEvents": True},
        ).add_to(fg)


def add_node_markers_from_graph(
    fg: folium.FeatureGroup, graph, tree_manager: BDONiceTreeManager, color: str | None = None
):
    """Add node markers with original styling, overlaying influence pie charts where relevant."""
    cmap = plt.get_cmap("tab20")
    bottleneck_keys = tree_manager.get_bottleneck_nodes(as_waypoints=True)
    bottleneck_keys = sorted(bottleneck_keys)
    bottleneck_colors = {bottleneck_keys[i]: cmap(i) for i in range(len(bottleneck_keys))}

    for node in graph.nodes():
        node_color = color
        node_key = node["waypoint_key"]
        cost = node["need_exploration_point"]
        node_is_bottleneck = node_key in bottleneck_keys

        lng = node["position"]["x"] / TILE_SCALE  # Scaled coordinates
        lat = node["position"]["z"] / TILE_SCALE  # Scaled coordinates

        popup_text = f"Node Key: {node_key}, Cost: {cost}"
        radius = 4 if node["is_base_town"] else 10 if color is not None else 1
        radius = 8 if node_is_bottleneck else radius

        if node_key == 99999:
            popup_text += " (Super Root)"
            node_color = SUPER_ROOT_COLOR

        if node_color is None:
            if node["is_base_town"]:
                node_color = BASE_TOWN_COLOR
                fill_color = BASE_TOWN_COLOR
                fill_opacity = 0.0
            else:
                node_color = REGULAR_NODE_COLOR
                fill_color = REGULAR_NODE_COLOR
                fill_opacity = 0.0

        if node_is_bottleneck:
            node_color = "white"
            fill_color = plt_colors.to_hex(bottleneck_colors[node_key])
            fill_opacity = 1.0

        folium.CircleMarker(
            location=(lat, lng),
            radius=radius,
            color=node_color,
            fill=True,
            fill_color=fill_color,
            fill_opacity=fill_opacity,
            popup=popup_text,
            tooltip=popup_text,
        ).add_to(fg)

        influence_data = tree_manager.calculate_bottleneck_weights(node_key, as_waypoints=True)
        if influence_data:
            fig = plt.figure(figsize=(0.5, 0.5))
            fig.patch.set_alpha(0)
            ax = fig.add_subplot(111)

            sorted_keys = sorted(influence_data.keys())
            sizes = [influence_data[k] for k in sorted_keys]
            colors = [bottleneck_colors[k] for k in sorted_keys]
            influence_popup_text = ", ".join(f"{k}: {v}" for k, v in influence_data.items())
            popup_text += f"\nInfluence: {influence_popup_text}"

            ax.pie(sizes, colors=colors)

            buff = io.StringIO()
            plt.savefig(buff, format="SVG", transparent=True)
            buff.seek(0)
            svg_data = buff.read().replace("\n", "")
            plt.close(fig)

            folium.Marker(location=(lat, lng), icon=folium.DivIcon(html=svg_data), tooltip=popup_text).add_to(
                fg
            )


def add_terminal_sets_markers(
    m: folium.Map, graph: rx.PyGraph | rx.PyDiGraph
) -> tuple[dict[str, FeatureGroupSubGroup], folium.FeatureGroup | None]:
    """Add terminal sets using FeatureGroupSubGroup for hierarchical toggling."""
    if "terminal_sets" not in graph.attrs:
        print("Warning: terminal_sets attribute not found in graph.")
        return {}, None

    terminal_sets = graph.attrs["terminal_sets"]

    # As the name indicates, this is the master FeatureGroup for the terminals layer.
    fg_terminal_sets_master = folium.FeatureGroup(name="All Terminal Sets", show=True).add_to(m)
    assert isinstance(fg_terminal_sets_master, folium.FeatureGroup)

    terminal_set_feature_groups = {}

    for color_index, (root, terminal_set) in enumerate(terminal_sets.items()):
        layer_name = f"Terminal Set {chr(65 + color_index)}"
        # FeatureGroupSubGroup nests the terminal set under the master group
        fg_terminal_set = FeatureGroupSubGroup(fg_terminal_sets_master, name=layer_name, show=True).add_to(m)
        terminal_set_feature_groups[layer_name] = fg_terminal_set

        terminal_set_color = MARKER_COLORS[color_index % len(MARKER_COLORS)]

        # Root node marker setup
        root_node = graph[root]
        root_lng = root_node["position"]["x"] / TILE_SCALE
        root_lat = root_node["position"]["z"] / TILE_SCALE

        folium.Marker(
            location=(root_lat, root_lng),
            icon=folium.Icon(
                color=terminal_set_color,
                icon=f"{chr(97 + color_index)}",
                prefix="fa",
                extraClasses="fa-border",
            ),
            popup=f"Root Node Key: {root_node['waypoint_key']}, Cost: {root_node['need_exploration_point']}",
            tooltip=f"Root Node Key: {root_node['waypoint_key']}, Cost: {root_node['need_exploration_point']}",
        ).add_to(fg_terminal_set)

        # Terminal node markers setup
        for terminal in terminal_set:
            terminal_node = graph[terminal]
            terminal_lng = terminal_node["position"]["x"] / TILE_SCALE
            terminal_lat = terminal_node["position"]["z"] / TILE_SCALE

            folium.Marker(
                location=(terminal_lat, terminal_lng),
                icon=folium.Icon(color=terminal_set_color, icon=f"{chr(97 + color_index)}", prefix="fa"),
                popup=f"Terminal Node Key: {terminal_node['waypoint_key']}, Cost: {terminal_node['need_exploration_point']}",
                tooltip=f"Terminal Node Key: {terminal_node['waypoint_key']}, Cost: {terminal_node['need_exploration_point']}",
            ).add_to(fg_terminal_set)

    return terminal_set_feature_groups, fg_terminal_sets_master


def visualize_solution_graph(
    main_graph: rx.PyGraph | rx.PyDiGraph,
    subgraph: rx.PyGraph | rx.PyDiGraph | None = None,
):
    """
    Visualizes the game map with the solution graph.

    Args:
        main_graph (rx.PyGraph): The main graph.
        subgraph (rx.PyGraph, optional): The reduced subgraph. Defaults to None.
        true_optimal_nodes (rx.PyGraph, optional): The true optimal solution node list. Defaults to None.
        reduced_optimal_nodes (rx.PyGraph, optional): The reduced graph optimal solution node list. Defaults to None.
    """

    # This is the main map which provides the coordinate system for location and ui controls.
    m = folium.Map(
        crs="Simple",  # Don't change
        location=[0, 0],  # Don't change
        zoom_start=2,  # Don't change
        zoom_snap=0.25,
        tiles=None,
    )

    # The tiles need to be a pane fixed at the bottom layer for proper drawing layers.
    tile_pane = folium.map.CustomPane("tile_pane", z_index=1)
    m.add_child(tile_pane)

    # Don't change, the zoom levels are pretty critical on these tiles.
    tiles = os.path.join(ds.path(), "maptiles", "{z}", "{x}_{y}.webp")
    tile_layer = folium.TileLayer(
        name="BDO Router",
        attr="Map Tiles @ BDO",
        min_zoom=1,
        max_zoom=7,
        no_wrap=True,
        pane="tile_pane",
        show=True,
        tiles=tiles,
    )
    tile_layer.add_to(m)

    # These Feature Groups allow control of the UI elements and are used for the
    # z-order of the layers when we set the keep_in_front setting below.
    fg_all_nodes = folium.FeatureGroup(name="All Nodes", show=True)
    fg_main_graph_edges = folium.FeatureGroup(name="Main Graph Edges", show=True)
    fg_subgraph_edges = folium.FeatureGroup(name="Sub Graph Edges", show=True)
    fg_main_optimal_edges = folium.FeatureGroup(name="Main Graph Optimal Edges", show=True)
    fg_subgraph_optimal_edges = folium.FeatureGroup(name="Sub Graph Optimal Edges", show=True)

    # Only use nodes in the main_graph.
    # All other graphs have the same exploration nodes.
    assert isinstance(main_graph, rx.PyDiGraph)
    assert isinstance(subgraph, rx.PyDiGraph)
    # add_node_markers_from_graph(fg_all_nodes, main_graph)

    # For Tree Decomposition Bottlenecks
    rx_full = exploration_data.graph.copy()
    rx_undirected = rx_full.to_undirected(multigraph=False)
    nx_G = nx.Graph()
    for u, v in rx_undirected.edge_list():
        nx_G.add_edge(u, v)
    tree_manager = BDONiceTreeManager(nx_G, exploration_data)
    tree_manager.generate_nice_tree()

    add_node_markers_from_graph(fg_all_nodes, main_graph, tree_manager, color=None)
    add_node_markers_from_graph(fg_all_nodes, subgraph, tree_manager, color=SUBGRAPH_NODE_COLOR)

    # Add all given edges from each graph to their own feature group
    # for independent control.
    add_edges_from_graph(
        fg_main_graph_edges,
        main_graph,
        color=MAIN_GRAPH_EDGE_COLOR,
        weight=MAIN_GRAPH_EDGE_WEIGHT,
    )
    if subgraph is not None:
        add_edges_from_graph(
            fg_subgraph_edges,
            subgraph,
            color=SUBGRAPH_EDGE_COLOR,
            weight=SUBGRAPH_EDGE_WEIGHT,
        )

    # Terminal sets toggling is a bit trickier, see the called function
    # for more details but in short we have a master and independent controls.
    terminal_set_feature_groups, fg_terminal_sets_master = add_terminal_sets_markers(m, main_graph)
    assert fg_terminal_sets_master is not None

    # All Feature Groups are added to the map except the terminal groups which
    # got added in the add_terminal_sets_markers function.
    fg_all_nodes.add_to(m)
    fg_main_graph_edges.add_to(m)
    fg_subgraph_edges.add_to(m)
    fg_main_optimal_edges.add_to(m)
    fg_subgraph_optimal_edges.add_to(m)

    # NOTE: The keep_in_front order is critical!
    m.keep_in_front(
        fg_main_graph_edges,
        fg_subgraph_edges,
        fg_main_optimal_edges,
        fg_subgraph_optimal_edges,
        fg_all_nodes,
        fg_terminal_sets_master,
        *terminal_set_feature_groups.values(),
    )

    # Grouped Layer Control for everything except Terminal Sets which is
    # handled below as its own LayerControl.
    group_layer_control = GroupedLayerControl(
        groups={
            "Base": [fg_all_nodes, fg_main_graph_edges, fg_subgraph_edges],
            "Optimal": [fg_main_optimal_edges, fg_subgraph_optimal_edges],
        },
        exclusive_groups=False,
        collapsed=False,
    )

    # Add the LayerControl after the tile layer
    folium.LayerControl(collapsed=False).add_to(m)
    group_layer_control.add_to(m)

    # Add the graph stats to the map
    stats_html = f"""
        <div style="position:absolute; z-index:100000; left:10px; top:10px;
                    background-color:white; padding:10px; border:1px solid black;">
            <h2>Graph/Solution Stats</h2>
            <p>Main Graph Nodes: {len(main_graph.nodes())}</p>
            <p>Main Graph Edges: {len(main_graph.edge_list())}</p>"""
    if subgraph:
        stats_html += f"""
            <p>Sub Graph Nodes: {len(subgraph.nodes())}</p>
            <p>Sub Graph Edges: {len(subgraph.edge_list())}</p>"""
    stats_html += """
        </div>
    """
    root = m.get_root()
    if isinstance(root, branca.element.Figure):  # (mostly for Pylance)
        root.html.add_child(folium.Element(stats_html))

    tmp_dir = tempfile.gettempdir()
    map_file = os.path.join(tmp_dir, "bdo_map.html")
    m.save(map_file)
    print(f"Map saved to {map_file}. Opening in your browser...")
    webbrowser.open("file://" + map_file)


def visualize_with_terminals(
    main_graph: rx.PyGraph | rx.PyDiGraph,
    subgraph: rx.PyGraph | rx.PyDiGraph | None = None,
    terminals: dict[int, int] | None = None,
):
    """
    Visualizes the game map with the solution graph.

    Args:
        main_graph (rx.PyGraph): The main graph used for background layer.
        subgraph (rx.PyGraph, optional): The reduced subgraph. Defaults to None.)
        terminals (dict, optional): terminal, root mapping. Defaults to None.
    """
    # TODO: Write this up to be part of the pipeline
    pass


if __name__ == "__main__":
    """Example usage"""
    # Main graph (background)
    config = {}
    config["exploration_data"] = {"directed": True, "edge_weighted": False, "omit_great_ocean": True}

    exploration_data = get_exploration_data()

    # MARK: Subgraph
    # fmt:off
    # indicate the {terminal: root, ... } pairs dict

    # Failing test case 1
    # query 325,602 1657,1649 635,604 1710,1691 629,604 675,601 1339,1301 1878,1853 1797,1795 1791,1795 
    # terminals={325: 602, 1657: 1649, 635: 604, 1710: 1691, 629: 604, 675: 601, 1339: 1301, 1878: 1853, 1797: 1795, 1791: 1795}
    # #     old [ 325, 307, 373, 669, 602, 1657, 1658, 1649, 635, 634, 604, 1710, 1703, 1740, 1691, 629, 628, 633, 601, 621, 632, 675, 652, 375, 1339, 1301, 1878, 1877, 1853, 1797, 1781, 1795, 1791, 1789, 1790 ] 36 CP
    # old = set([ 325, 307, 373, 669, 602, 1657, 1658, 1649, 635, 634, 604, 1710, 1703, 1740, 1691, 629, 628, 633, 601, 621, 632, 675, 652, 375, 1339, 1301, 1878, 1877, 1853, 1797, 1781, 1795, 1791, 1789, 1790 ] )
    # #     wasm [ 307, 325, 373, 601, 602, 604, 621, 628, 629, 632, 633, 634, 635, 652, 653, 661, 669, 675, 1301, 1339, 1649, 1657, 1658, 1691, 1703, 1710, 1740, 1781, 1791, 1792, 1793, 1795, 1797, 1853, 1877, 1878 ] 37 CP
    # wasm = set([ 307, 325, 373, 601, 602, 604, 621, 628, 629, 632, 633, 634, 635, 652, 653, 661, 669, 675, 1301, 1339, 1649, 1657, 1658, 1691, 1703, 1710, 1740, 1781, 1791, 1792, 1793, 1795, 1797, 1853, 1877, 1878 ] )


    # # Failing test case 2
    # # query 1793,1781 663,604 670,602 1372,1002 1863,1785 1890,1853 628,604 1836,1834 1659,1649 1034,1002
    # terminals = {1793: 1781, 663: 604, 670: 602, 1372: 1002, 1863: 1785, 1890: 1853, 628: 604, 1836: 1834, 1659: 1649, 1034: 1002}
    # # old [ 1793, 1795, 1781, 663, 665, 601, 621, 632, 635, 634, 604, 670, 654, 602, 1372, 1097, 1096, 1002, 1863, 1864, 1865, 1867, 1868, 1784, 1785, 1890, 1870, 1860, 1852, 1853, 628, 633, 1836, 1835, 1834, 1659, 1649, 1034, 1004, 1005 ] wasm [ 601, 602, 604, 621, 628, 632, 633, 634, 635, 654, 663, 665, 670, 1002, 1004, 1005, 1034, 1096, 1097, 1372, 1649, 1659, 1781, 1784, 1785, 1790, 1793, 1834, 1835, 1836, 1852, 1853, 1860, 1863, 1864, 1865, 1867, 1868, 1870, 1890 ]
    # old = set([1793, 1795, 1781, 663, 665, 601, 621, 632, 635, 634, 604, 670, 654, 602, 1372, 1097, 1096, 1002, 1863, 1864, 1865, 1867, 1868, 1784, 1785, 1890, 1870, 1860, 1852, 1853, 628, 633, 1836, 1835, 1834, 1659, 1649, 1034, 1004, 1005 ])
    # # wasm [ 601, 602, 604, 621, 628, 632, 633, 634, 635, 654, 663, 665, 670, 1002, 1004, 1005, 1034, 1096, 1097, 1372, 1649, 1659, 1781, 1784, 1785, 1790, 1793, 1834, 1835, 1836, 1852, 1853, 1860, 1863, 1864, 1865, 1867, 1868, 1870, 1890]
    # wasm = set([ 601, 602, 604, 621, 628, 632, 633, 634, 635, 654, 663, 665, 670, 1002, 1004, 1005, 1034, 1096, 1097, 1372, 1649, 1659, 1781, 1784, 1785, 1790, 1793, 1834, 1835, 1836, 1852, 1853, 1860, 1863, 1864, 1865, 1867, 1868, 1870, 1890])

    # 325,602 635,604 629,604 675,601
    terminals = {}
    # old []
    # wasm = set([1, 1668, 301, 302, 371, 373, 375, 6, 601, 602, 604, 651, 652])

    # indicate the solution nodes (paths to highlight)
    highlights = {}

    # fmt:on

    G = exploration_data.graph
    if SUPER_ROOT in terminals.values():
        G = exploration_data.super_graph
    assert isinstance(G, rx.PyDiGraph)

    set_graph_terminal_sets_attribute(G, terminals)

    highlights.update(key for key in terminals.keys())
    highlights.update(key for key in terminals.values())
    waypoint_to_index = {node["waypoint_key"]: i for i, node in enumerate(G.nodes())}
    highlight_indices = [waypoint_to_index[key] for key in highlights]
    highlight_graph = subgraph_stable(G, highlight_indices)

    # Cost of highlighted nodes
    cost = sum(node["need_exploration_point"] for node in highlight_graph.nodes())
    print(f"Cost of highlighted nodes: {cost}")

    # Cost per connected component
    from rustworkx import strongly_connected_components

    for component in strongly_connected_components(highlight_graph):
        costs = [(G[node]["waypoint_key"], G[node]["need_exploration_point"]) for node in component]
        cost = sum(G[node]["need_exploration_point"] for node in component)
        print(f"Component: {costs}")
        print(f"Cost of component: {cost}")

    # # # Generate web page using Folium - browser will open when complete.
    visualize_solution_graph(
        main_graph=G,
        subgraph=highlight_graph,
    )
